"""added material to question

Revision ID: 247f1ddeec6c
Revises: e2a80ee9c99a
Create Date: 2023-12-09 20:32:50.390628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247f1ddeec6c'
down_revision = 'e2a80ee9c99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('material', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'material')
    # ### end Alembic commands ###