bot_token: "6620540601:AAGeGw_Xs4IeoXBTVeYd_eAU5HydlKBC3vU"
admins:  []
chat:
database_uri: postgresql+asyncpg://postgres:postgres@localhost:5432/examination_bot
redis_host: localhost
redis_port: 6379
redis_db: 0
redis_password: None
redis_prefix: bot_fsm

